language: python
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      env: TARGET=svg
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      env: TARGET=android
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      env: TARGET=win
    - os: osx
      language: generic
      env: TARGET=osx
      osx_image: xcode7.3
    - os: osx
      language: generic
      env: TARGET=ios
      osx_image: xcode7.2
    - os: osx
      language: generic
      env: TARGET=ios
      osx_image: xcode7.3
install: true
before_script:
  - source ./scripts/install_deps.sh
  - pip install -r requirements.txt
  - pip install .
script:
  - ./scripts/run_target.sh
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openjdk-7-jre-headless
      - openjdk-7-jdk
      - imagemagick
      - gettext
      - autopoint
      - build-essential
      - automake
      - autoconf

