language: python
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
        # Use generic language for osx
        - os: osx
          language: generic
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update && brew install python3 && virtualenv ~/venv -p python3 && source ~/venv/bin/activate;
      fi
install:
    - pip install -r requirements.txt
    - pip install .
script:
    - kbdgen -h
