language: python
matrix:
  include:
    - os: linux
      python: 3.5
      env: TARGET=svg
    - os: linux
      python: 3.5
      env: TARGET=android
    - os: linux
      python: 3.5
      env: TARGET=win
    - os: osx
      language: generic
      env: TARGET=osx
    - os: osx
      language: generic
      env: TARGET=ios
before_install:
  - source ./scripts/install_deps.sh
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - ./scripts/run_target.sh
addons:
  apt:
    packages:
      - openjdk-7-jre-headless
      - openjdk-7-jdk
      - imagemagick
